SET TERM ON
SET ECHO OFF

DEFINE SCHEMA_OBJ = '&1'
DEFINE OBJECT_NAME = '&2'
DEFINE OBJECT_TYPE = '&3'
DEFINE SURFIX = '.sql'
DEFINE DOT = '.'
DEFINE FILE_NAME = '&1&DOT&2&DOT&3&SURFIX'

--debug
--select '&FILE_NAME' x from dual; 

-- spool src
PROMPT Export DB source code
SET TERM OFF
SPOOL '&FILE_NAME' 
SET LINESIZE 4000
SET ECHO OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
SET AUTO OFF
SET TRIMSPOOL ON
SET TERM OFF
SET EMB ON
SELECT CASE WHEN line = 1 THEN 'CREATE OR REPLACE '||text ELSE text END text_line
FROM all_source
WHERE owner = '&SCHEMA_OBJ'
AND name = '&OBJECT_NAME'
AND type = '&OBJECT_TYPE'
ORDER BY line;
SPOOL OFF

